### ISSUE TITLE
[BUG]: TypeError: o.license is null

### ISSUE THREAD

**Issue by rgl** [dgraph-io/ratel#314]
### What version of Ratel are you using?

v21.12.0

### What you did.

Starting `dgraph zero --enterprise_license=/dev/null` crashes ratel.

Here's my docker compose file:

```yml
services:
  zero:
    image: dgraph/dgraph:v24.0.0
    volumes:
      - zero:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command:
      - dgraph
      - zero
      - --telemetry=sentry=false
      - --enterprise_license=/dev/null
      - --my=zero:5080
  alpha:
    image: dgraph/dgraph:v24.0.0
    volumes:
      - alpha:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command:
      - dgraph
      - alpha
      - --telemetry=sentry=false
      - --my=alpha:7080
      - --zero=zero:5080
  ratel:
    image: dgraph/ratel:v21.12.0
    ports:
      - 8000:8000
    restart: on-failure
volumes:
  zero:
  alpha:
```

### What happened.

Opening ratel at http://localhost:8000 shows nothing and the browser console shows something like:

```
 TypeError: o.license is null
    oh ClusterPage.js:136
    oh ClusterPage.js:286
    React 8
    unstable_runWithPriority scheduler.production.min.js:289
```

### What you expect to happen.

Ratel to worl.

### Can we reproduce the issue?

use the above docker compose file as:

```bash
docker compose up --detach
xdg-open http://localhost:8000
docker compose down --volumes
```
